import type { Metadata } from "next";
import { Theme } from '@radix-ui/themes';
import '../styles/globals.css';


export const metadata: Metadata = {
  title: "Maalem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  );
}
