import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Kufino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@100,200,300,400,500,700,800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://api.fontshare.com/v2/css?f[]=comico@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
